---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: alpine
    commands:
      - export PATH=$PATH:.
      - apk add bash
      - sleep 30
      - red-shu-exec.sh

trigger:
  event:
    - push
    - pull_request
